# crawler/.air.toml
root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
full_bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
include_dir = []
exclude_regex = ["_test.go"]
exclude_file = []
delay = 1000
stop_on_root = false
send_interrupt = false
kill_delay = 500

[misc]
clean_on_exit = true

[log]
prefix = ""
color = "green"

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"